FROM golang:alpine as builder

WORKDIR /app 

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o app-code-education .

FROM scratch

WORKDIR /app

COPY --from=builder /app/app-code-education /usr/bin/

ENTRYPOINT ["app-code-education"]